"""Output formatters for generated content."""
from typing import Dict, Any, Optional
import json
import re


class OutputFormatter:
    """Format generated content for various output types."""
    
    def format_markdown(self, content: str, metadata: Optional[Dict] = None) -> str:
        """Format content as clean markdown."""
        # Ensure proper heading hierarchy
        lines = content.split("\n")
        formatted_lines = []
        
        for line in lines:
            # Fix heading levels
            if line.startswith("#"):
                # Ensure space after #
                match = re.match(r"^(#+)(\S)", line)
                if match:
                    line = match.group(1) + " " + line[len(match.group(1)):]
            
            formatted_lines.append(line)
        
        formatted = "\n".join(formatted_lines)
        
        # Add metadata header if provided
        if metadata:
            header = self._create_metadata_header(metadata)
            formatted = header + "\n\n" + formatted
        
        return formatted
    
    def format_json(self, content: str, metadata: Optional[Dict] = None) -> str:
        """Format content as JSON."""
        result = {
            "content": content,
            "format": "markdown"
        }
        
        if metadata:
            result["metadata"] = metadata
        
        return json.dumps(result, indent=2)
    
    def format_code(
        self,
        code: str,
        language: str,
        include_header: bool = True
    ) -> str:
        """Format code with proper structure."""
        formatted = code.strip()
        
        if include_header:
            header_comment = self._get_language_comment(language)
            header = f"""{header_comment}
{header_comment} Generated by AI Learning Platform
{header_comment} Language: {language}
{header_comment}

"""
            formatted = header + formatted
        
        return formatted
    
    def format_for_display(
        self,
        content: str,
        content_type: str,
        sources: Optional[Dict] = None
    ) -> Dict[str, Any]:
        """Format content for frontend display."""
        result = {
            "content": content,
            "type": content_type,
            "formatted": True
        }
        
        if sources:
            result["sources"] = {
                "course": sources.get("course", []),
                "web": sources.get("web", []),
                "course_count": sources.get("course_citation_count", 0),
                "web_count": sources.get("web_citation_count", 0)
            }
            
            # Calculate source mix for display
            total = result["sources"]["course_count"] + result["sources"]["web_count"]
            if total > 0:
                result["source_mix"] = {
                    "course_percentage": round(result["sources"]["course_count"] / total * 100),
                    "web_percentage": round(result["sources"]["web_count"] / total * 100)
                }
        
        return result
    
    def _create_metadata_header(self, metadata: Dict) -> str:
        """Create a metadata header for markdown."""
        lines = ["---"]
        
        for key, value in metadata.items():
            if isinstance(value, list):
                value = ", ".join(str(v) for v in value)
            lines.append(f"{key}: {value}")
        
        lines.append("---")
        return "\n".join(lines)
    
    def _get_language_comment(self, language: str) -> str:
        """Get comment syntax for a language."""
        comment_styles = {
            "python": "#",
            "javascript": "//",
            "typescript": "//",
            "java": "//",
            "cpp": "//",
            "c": "//",
            "csharp": "//",
            "go": "//",
            "rust": "//",
            "sql": "--",
            "ruby": "#",
            "php": "//"
        }
        return comment_styles.get(language.lower(), "#")


# Singleton instance
_formatter = None


def get_formatter() -> OutputFormatter:
    """Get or create formatter singleton."""
    global _formatter
    if _formatter is None:
        _formatter = OutputFormatter()
    return _formatter
